# Display name and URL of the site
site_name: 'Faculty Guide for Electronics'
#site_url: 'https://faculty.guide/' # For production only

# Project's GitHub repository
#repo_name: 'electronics-lnu/faculty-guide'
#repo_url: 'https://github.com/electronics-lnu/faculty-guide'

nav:
  - 'Стартова сторінка': index.md
  - 'Про навчальний процес':
    - for-freshmen/education/index.md
    - for-freshmen/education/session.md
    - for-freshmen/education/scholarships.md
  - 'Життя і буття студента':
    - for-freshmen/residence/index.md
    - for-freshmen/residence/internet-access.md
    - for-freshmen/residence/gov-registration.md
    - for-freshmen/residence/medicaid.md
  - 'Твоє студентське життя':
    - for-freshmen/lifestyle/index.md
    - for-freshmen/lifestyle/organizations.md
    - for-freshmen/lifestyle/events.md
    - for-freshmen/lifestyle/international.md
    - for-freshmen/lifestyle/circles.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

theme:
  name: material
  custom_dir: mkdocs_overrides
  language: uk
  logo: '_assets/img/faculty_logo.jpg'
  favicon: '_assets/img/faculty_logo.jpg'
  features:
    - announce.dismiss
    - navigation.expand
    #- navigation.indexes
    - navigation.instant
    - navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: 'Перейти на Темний бік Сили'
      primary: indigo
      accent: indigo

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 'Перейти на Світлий бік Сили'
      primary: indigo
      accent: indigo
  font:
    text: 'Roboto'
    code: 'Source Code Pro'

plugins:
  - search

extra:
  generator: false
  social:
    # Telegram channel link
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/electronics_lnu'
    # Facebook page link
    - icon: fontawesome/brands/facebook
      link: 'https://facebook.com/electronics.lnu'
    # Instagram page link
    - icon: fontawesome/brands/instagram
      link: 'https://instagram.com/electronics_lnu'
    # YouTube channel link
    - icon: fontawesome/brands/youtube
      link: 'https://youtube.com/channel/UCrKI0wrgSLhqOUESLiTk4UA'
  analytics:
    provider: google
    property: G-GMPPDCQN2S # Ідентифікатор для домену в зоні GitHub.IO

copyright: >
  Copyright &copy; 2021-2022, Студенти <a href='https://electronics.lnu.edu.ua/' target='_blank'>Факультету електроніки та комп'ютерних технологій</a>
  <a href='https://lnu.edu.ua/' target='_blank'>ЛНУ імені Івана Франка</a>.
  Створено у рамках ініціативи <a href='https://t.me/lnu_guide'>#lnu_guide for electronics</a>.

extra_css:
  - _assets/css/extra.css