name: Publish Faculty Guide to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy MkDocs website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch for GitHub repository
        uses: actions/checkout@v2

      - name: Build and deploy static MkDocs website
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: guide.elct.lnu.edu.ua
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: requirements.txt